// app/privacy/page.tsx
export default function PrivacyPolicy() {
	return (
		<div className="max-w-3xl mx-auto px-4 py-10 text-gray-800">
			<h1 className="text-2xl font-bold mb-6 text-center">
				INFORMATIVA SULLA PRIVACY AI SENSI DEL REGOLAMENTO (UE) 2016/679 (GDPR)
			</h1>

			<p className="mb-4">
				<strong>Associazione di Volontariato “CUORE A 4 ZAMPE ODV”</strong><br />
				Sede legale: Via della Miniera 11 – 50031 Barberino di Mugello (FI)<br />
				Cod. Fisc. 90036700481<br />
				Email: <a href="mailto:cuorea4zampebarberino@gmail.com" className="text-blue-600 underline">cuorea4zampebarberino@gmail.com</a>
			</p>

			<section className="mb-6">
				<h2 className="text-lg font-semibold mb-2">1. Titolare del trattamento:</h2>
				<p>
					Il Titolare del trattamento è l’Associazione “CUORE A 4 ZAMPE ODV”, contattabile all’indirizzo sopra indicato.
				</p>
			</section>

			<section className="mb-6">
				<h2 className="text-lg font-semibold mb-2">2. Finalità del trattamento:</h2>
				<ul className="list-disc list-inside space-y-1">
					<li>gestione delle richieste di affido/adozione e soccorso animali</li>
					<li>gestione dei soci e dei volontari</li>
					<li>comunicazioni istituzionali e operative dell’associazione</li>
					<li>obblighi legali e assicurativi</li>
				</ul>
			</section>

			<section className="mb-6">
				<h2 className="text-lg font-semibold mb-2">3. Tipologie di dati trattati:</h2>
				<ul className="list-disc list-inside space-y-1">
					<li>Dati identificativi (nome, cognome)</li>
					<li>Dati di contatto (telefono, email, indirizzo)</li>
					<li>Immagini e video (solo con consenso)</li>
					<li>Eventuali dati sanitari degli animali adottati/affidati</li>
				</ul>
			</section>

			<section className="mb-6">
				<h2 className="text-lg font-semibold mb-2">4. Base giuridica del trattamento:</h2>
				<p>
					Il trattamento si basa sul consenso dell’interessato (art. 6, par. 1, lett. a) e sull’adempimento di obblighi legali o statutari (art. 6, par. 1, lett. c).
				</p>
			</section>

			<section className="mb-6">
				<h2 className="text-lg font-semibold mb-2">5. Modalità del trattamento:</h2>
				<p>
					Il trattamento è effettuato in modo lecito, corretto e trasparente, anche con strumenti elettronici. I dati sono conservati per il tempo necessario alle finalità sopra indicate.
				</p>
			</section>

			<section className="mb-6">
				<h2 className="text-lg font-semibold mb-2">6. Destinatari dei dati:</h2>
				<p>I dati non saranno oggetto di diffusione, salvo obblighi legali. Potranno essere comunicati a:</p>
				<ul className="list-disc list-inside space-y-1">
					<li>enti pubblici (es. ASL, Comuni)</li>
					<li>assicurazioni (per volontari)</li>
					<li>collaboratori interni autorizzati al trattamento</li>
				</ul>
			</section>

			<section className="mb-6">
				<h2 className="text-lg font-semibold mb-2">7. Diritti dell’interessato:</h2>
				<p>
					L’interessato può esercitare i diritti di cui agli articoli 15-22 del GDPR (accesso, rettifica, cancellazione, opposizione, limitazione, portabilità). Le richieste vanno inviate a: <span className="text-blue-600">[email dell’associazione]</span>.
				</p>
			</section>

			<div className="mt-10">
				<a
					href="/Informativa_Privacy_Cuore_A_4_Zampe_ODV.pdf"
					download
					className="inline-block px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition"
				>
					Scarica l’informativa in PDF
				</a>
			</div>
		</div>
	);
}

// src/routes/privacy/+page.svelte
<script>
</script>

<main class="max-w-3xl mx-auto px-4 py-10 text-gray-800">
 	<h1 class="text-2xl font-bold mb-6 text-center">INFORMATIVA SULLA PRIVACY AI SENSI DEL REGOLAMENTO (UE) 2016/679 (GDPR)</h1>

 	<p class="mb-4">
 		<strong>Associazione di Volontariato “CUORE A 4 ZAMPE ODV”</strong><br />
 		Sede legale: Via della Miniera 11 – 50031 Barberino di Mugello (FI)<br />
 		Cod. Fisc. 90036700481<br />
 		Email: <a href="mailto:cuorea4zampebarberino@gmail.com" class="text-blue-600 underline">cuorea4zampebarberino@gmail.com</a>
 	</p>

 	<section class="mb-6">
 		<h2 class="text-lg font-semibold mb-2">1. Titolare del trattamento:</h2>
 		<p>Il Titolare del trattamento è l’Associazione “CUORE A 4 ZAMPE ODV”, contattabile all’indirizzo sopra indicato.</p>
 	</section>

 	<section class="mb-6">
 		<h2 class="text-lg font-semibold mb-2">2. Finalità del trattamento:</h2>
 		<ul class="list-disc list-inside space-y-1">
 			<li>gestione delle richieste di affido/adozione e soccorso animali</li>
 			<li>gestione dei soci e dei volontari</li>
 			<li>comunicazioni istituzionali e operative dell’associazione</li>
 			<li>obblighi legali e assicurativi</li>
 		</ul>
 	</section>

 	<section class="mb-6">
 		<h2 class="text-lg font-semibold mb-2">3. Tipologie di dati trattati:</h2>
 		<ul class="list-disc list-inside space-y-1">
 			<li>Dati identificativi (nome, cognome)</li>
 			<li>Dati di contatto (telefono, email, indirizzo)</li>
 			<li>Immagini e video (solo con consenso)</li>
 			<li>Eventuali dati sanitari degli animali adottati/affidati</li>
 		</ul>
 	</section>

 	<section class="mb-6">
 		<h2 class="text-lg font-semibold mb-2">4. Base giuridica del trattamento:</h2>
 		<p>Il trattamento si basa sul consenso dell’interessato (art. 6, par. 1, lett. a) e sull’adempimento di obblighi legali o statutari (art. 6, par. 1, lett. c).</p>
 	</section>

 	<section class="mb-6">
 		<h2 class="text-lg font-semibold mb-2">5. Modalità del trattamento:</h2>
 		<p>Il trattamento è effettuato in modo lecito, corretto e trasparente, anche con strumenti elettronici. I dati sono conservati per il tempo necessario alle finalità sopra indicate.</p>
 	</section>

 	<section class="mb-6">
 		<h2 class="text-lg font-semibold mb-2">6. Destinatari dei dati:</h2>
 		<p>I dati non saranno oggetto di diffusione, salvo obblighi legali. Potranno essere comunicati a:</p>
 		<ul class="list-disc list-inside space-y-1">
 			<li>enti pubblici (es. ASL, Comuni)</li>
 			<li>assicurazioni (per volontari)</li>
 			<li>collaboratori interni autorizzati al trattamento</li>
 		</ul>
 	</section>

 	<section class="mb-6">
 		<h2 class="text-lg font-semibold mb-2">7. Diritti dell’interessato:</h2>
 		<p>L’interessato può esercitare i diritti di cui agli articoli 15-22 del GDPR (accesso, rettifica, cancellazione, opposizione, limitazione, portabilità). Le richieste vanno inviate a: <span class="text-blue-600">[email dell’associazione]</span>.</p>
 	</section>

 	<div class="mt-10">
 		<a href="/Informativa_Privacy_Cuore_A_4_Zampe_ODV.pdf" download class="inline-block px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition">Scarica l’informativa in PDF</a>
 	</div>
</main>
